create database locadora;
use locadora;


CREATE TABLE FUNCIONARIO(
 IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
 NOME VARCHAR(250) NOT NULL,
 DTNASCIMENTO VARCHAR(10) NOT NULL,
 CPF CHAR(14) NOT NULL,
 EMAIL VARCHAR(250) NOT NULL,
 CARGO VARCHAR(250) NOT NULL,
 LOGIN VARCHAR(250) NOT NULL,
 SENHA VARCHAR(20) NOT NULL,
 ATIVO TINYINT(1) NOT NULL,
 ENABLE TINYINT(1) NOT NULL,
 PRIMARY KEY(IDFUNCIONARIO)
);

CREATE TABLE CLIENTE(
IDCLIENTE INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(250) NOT NULL,
IDADE INT(3) NOT NULL,
DTNASCIMENTO VARCHAR(10) NOT NULL,
TELFIXO CHAR(15) NOT NULL,
TELCEL CHAR(16) NOT NULL,
EMAIL VARCHAR(250) NOT NULL,
CNH INT NOT NULL,
RG CHAR(13),
CPF CHAR(14),
ENABLE TINYINT(1) NOT NULL,
PRIMARY KEY(IDCLIENTE)
);


CREATE TABLE VEICULO(
IDVEICULO INT NOT NULL AUTO_INCREMENT,
MODELO VARCHAR(250) NOT NULL,
CATEGORIA VARCHAR(250) NOT NULL,
ANO VARCHAR(4) NOT NULL,
PLACA CHAR(11) NOT NULL,
MARCA VARCHAR(250) NOT NULL,
NUMERODOC VARCHAR(11) NOT NULL,
CARACTERISTICAS LONGTEXT NOT NULL,
IMAGEM BLOB,
ENABLE TINYINT(1) NOT NULL,
PRIMARY KEY(IDVEICULO)
);

CREATE TABLE LOCACAO(
CODIGO VARCHAR(250) NOT NULL,
IDLOCACAO INT NOT NULL AUTO_INCREMENT,
IDCLIENTE INT NOT NULL,
IDFUNCIONARIO INT NOT NULL,
IDVEICULO INT NOT NULL,
PROTECAO VARCHAR(250) NOT NULL,
PRECO_TOTAL REAL NOT NULL,
DIARETIRA DATE NOT NULL,
DIAENTREGA DATE NOT NULL,
PRIMARY KEY(IDLOCACAO),
CONSTRAINT FK_IDCLIENTEORDER FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
CONSTRAINT FK_IDFUNCIONARIOORDER FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
CONSTRAINT FK_IDVEICULOORDER FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO)
);

CREATE TABLE FILIAL(
IDFILIAL INT NOT NULL AUTO_INCREMENT,
CNPJ VARCHAR(18) NOT NULL,
EMAIL VARCHAR(250) NOT NULL,
TELFIXO CHAR(15) NOT NULL,
TELCEL CHAR(16) NOT NULL,
ENDERECO VARCHAR(250) NOT NULL,
NUMERO VARCHAR(4) NOT NULL,
COMPLEMENTO VARCHAR(4) NOT NULL,
CEP VARCHAR(10) NOT NULL,
CIDADE VARCHAR(50) NOT NULL,
ESTADO VARCHAR(50) NOT NULL,
PRIMARY KEY(IDFILIAL)
);

CREATE TABLE LIGACAOFILIAL(
IDFILIAL INT NOT NULL,
IDCLIENTE INT,
IDFUNCIONARIO INT,
IDVEICULO INT,
PRIMARY KEY(IDFILIAL),
CONSTRAINT FK_IDCLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
CONSTRAINT FK_IDFUNCIONARIO FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
CONSTRAINT FK_IDVEICULO FOREIGN KEY (IDVEICULO) REFERENCES VEICULO(IDVEICULO)
);


/*INSERTS FUNCIONARIO*/
INSERT INTO FUNCIONARIO(NOME,DTNASCIMENTO,CPF,EMAIL,LOGIN,SENHA,CARGO,ATIVO,ENABLE) VALUES('RODRIGO','1995-09-05','488.488.478-47','RODRIGOFARIA@HOTMAIL.COM','RODRIGO','123','ADMINISTRADOR',1,1);
INSERT INTO FUNCIONARIO(NOME,DTNASCIMENTO,CPF,EMAIL,LOGIN,SENHA,CARGO,ATIVO,ENABLE) VALUES('JUAN','1990-11-25','588.475.412-20','JUAN-O-GATO@GMAIL.COM','JUAZINHO','TODDINHO','GERENTE DE TI',1,1);
INSERT INTO FUNCIONARIO(NOME,DTNASCIMENTO,CPF,EMAIL,LOGIN,SENHA,CARGO,ATIVO,ENABLE) VALUES('ALINE FARIAS','1980-10-30','154.264.451-89','ALINE-SAFADADOGRAU@HOTMAIL.COM','ALINE','1510','ATENDENTE',1,1);


/*INSERTS CLIENTE*/
INSERT INTO CLIENTE(NOME,IDADE,DTNASCIMENTO,RG,CPF,EMAIL,TELFIXO,TELCEL,CNH,ENABLE) VALUES('RODRIGO',25,'1995-09-05','40.145.478-5','488.488.478-47','RODRIGOFARIA@HOTMAIL.COM','5522-3654','95412-3654',654,1);
INSERT INTO CLIENTE(NOME,IDADE,DTNASCIMENTO,RG,CPF,EMAIL,TELFIXO,TELCEL,CNH,ENABLE) VALUES('JUAN',30,'1990-11-25','50.255.487-7','588.475.412-20','JUAN-O-GATO@GMAIL.COM','5521-4536','95487-5123','546',1);
INSERT INTO CLIENTE(NOME,IDADE,DTNASCIMENTO,RG,CPF,EMAIL,TELFIXO,TELCEL,CNH,ENABLE) VALUES('ALINE FARIAS',19,'1990-11-25','10.648.124-9','154.264.451-89','ALINE-SAFADADOGRAU@HOTMAIL.COM','5512-2548','95487-5214',4654,1);

/*INSERTS VEIUCLO*/
INSERT INTO VEICULO(MODELO,CATEGORIA,ANO,PLACA,MARCA,NUMERODOC,CARACTERISTICAS,ENABLE) VALUES('C3','CATEGORIA A','2012','AABCS-41555','FORD',44654,'CARRO ARRRUMADIN',1);


select * from funcionario;
select * from veiculo;